spring:
  application:
    name: farming-App
  datasource:
    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/ndnrajrd
    username: ndnrajrd
    password: X4twvDP7ZCgh-Llw9NdgyfnJaJxMve6f
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: Facebook
    password: fcmhpukoxswqtjhe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: redis-16904.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 16904
      password: B8XOR0A25RpczBOJooae1KjwWdLCxnv2
  elasticsearch:
    username: elastic
    password: 270703
    uris: http://localhost:9200

open:
  api:
    title: API document
    version: v1.0.0
    description: Mo ta api service
    serverUrl: https://farming-app-production.up.railway.app/
    serverName: server test


# Cấu hình URL và token của API GHN
ghn:
    api:
      url: https://online-gateway.ghn.vn
      token: 199acb3e-3b64-11ef-a3f8-86d541dd462b
      shopid: 5151825



